### ISSUE TITLE
Make the footer more consistent with the website UX 

### ISSUE THREAD

**Issue by KartikChinda** [OctobearHub/octobear.org#17]
**Is your feature request related to a problem? Please describe.**
The current footer stands out a lot from the rest of the website, if this is something the moderators would want changed, I'd love to work on it. 

**Describe the solution you'd like**
Changing the background colour of the footer and the text colour to a colour that blends in more with the rest of the color scheme.

**Comment by clebsonf** [comment]
Sure! It would also be nice to put social links to discord, to the repository, to Instagram and LinkedIn:

https://www.instagram.com/octobear.hub/

https://www.linkedin.com/company/octobear/
