### ISSUE TITLE
Can I add a facedetection Program as well?

### ISSUE THREAD

**Issue by fineanmol** [OctobearHub/octobear.org#2]
@clebsonf I have made a Face Detection Program. Can I contribute that as well?

**Comment by clebsonf** [comment]
We can create a section on the site for community projects, so you could add the projects that you think are worthy of mention. 
The "dynamic" data I'm putting in the directory:
 https://github.com/OctobearHub/octobear.org/tree/main/src/assets/data

So we can make it simpler for no-code contributors.
