### ISSUE TITLE
Create a security policy

### ISSUE THREAD

**Issue by whoisclebs** [OctobearHub/octobear.org#4]
We don't have a security policy yet, it's a good starting point for no-code contributors.

**Comment by rexdivakar** [comment]
Hey @clebsonf i would like to add this change to the src code.

**Comment by clebsonf** [comment]
Hello rexdivakar, as I haven't had any more updates from you, I'll release the issue to new contributors. If you want to work on it again, let me know so I can re-assign you.

**Comment by thevinitgupta** [comment]
I would like to work on this

**Comment by rexdivakar** [comment]
Hey @clebsonf sorry i was away a bit, yes i'm looking on this issue pls assign me abck

**Comment by clebsonf** [comment]
Hey there! I created a discussion for us to brainstorm about security policies. Any idea is welcome, we can follow from here together in this PR https://github.com/OctobearHub/octobear.org/discussions/36

**Comment by clebsonf** [comment]
@MarcosLudgerio Would you like to participate too?

**Comment by kartiksaxena532** [comment]
i would like to participate @clebsonf

**Comment by MarcosLudgerio** [comment]
Hi. Yes, I would like to contribue.
