### ISSUE TITLE
[Bug-Dev] Tag's description disappearing in dark mode when selected!

### ISSUE THREAD

**Issue by VitorAmrm** [OctobearHub/octobear.org#42]
**Describe the bug**
When any tag is in pressed, the description of the tag that is pressed dissapear

**To Reproduce**

1. Go to Resource Page
2. Click on any tag
3. Watch the behavior

**Expected behavior**
The tags description is expected to be visible

**Screenshots**
![Screenshot_11](https://user-images.githubusercontent.com/45771398/194433209-b127a1cb-fbf2-4fbf-be51-8a50539977e2.png)

**Additional context**
Occurs on Desktop and mobile browsers.

Tested on: Edge

**Comment by VitorAmrm** [comment]
If possible, I wanna work on it! Autarquia @clebsonf

**Comment by MarcosLudgerio** [comment]
Hi @VitorAmrm, I confirmed the bug. This even occurs. I tested it in chrome and had the same behavior.

**Comment by MarcosLudgerio** [comment]
If you need help. I would like work with this.

**Comment by VitorAmrm** [comment]
@MarcosLudgerio I just made a commit, you can review or add more features.

**Comment by clebsonf** [comment]
closes: #43
