### ISSUE TITLE
[Feature][Improvement] possibility to filter by multiple tags and deselect a tag!

### ISSUE THREAD

**Issue by VitorAmrm** [OctobearHub/octobear.org#44]
**Describe the solution you'd like**
I would like to filter by pressing in more than  one tag at a time, and deselect a tag that was previously selected

**Comment by VitorAmrm** [comment]
@clebsonf Autarquia, you agreed?

**Comment by MarcosLudgerio** [comment]
Yes, assign to us @clebsonf!
