### ISSUE TITLE
add new resources for community.

### ISSUE THREAD

**Issue by whoisclebs** [OctobearHub/octobear.org#5]
We need to add more resources for developers. Each one can contribute with some useful link for web development or for another context.

The data file can be found [here](https://github.com/OctobearHub/octobear.org/blob/main/src/assets/data/resources.json). Add more links in it in the following template:

```json
    {
        "title": "unDraw",
        "image": "https://user-images.githubusercontent.com/43012757/193366197-ebfb6708-2107-4189-923c-ce025dd6706a.png",
        "description": "Open-source illustrations for every project you can imagine and create.",
        "url": "https://undraw.co/",
        "tags": [
            "design",
            "ilustration"
        ]
    },
```

This issue can be used by as many users as they want. Just have a useful link.

**Comment by yesimhozman** [comment]
can you assign it to me?

**Comment by clebsonf** [comment]
of course @yesimhozman

**Comment by clebsonf** [comment]
Done! Pull request #6 accepted. Issue accepting for new contributions.

**Comment by bruceyboy86** [comment]
Can I contribute?

**Comment by clebsonf** [comment]
of course @bruceyboy86

**Comment by bruceyboy86** [comment]
Can you please check if I have write access to this repo?
I'm getting the following error when I try to fork:
remote: Permission to OctobearHub/octobear.org.git denied to bruceyboy86.
fatal: unable to access 'https://github.com/OctobearHub/octobear.org.git/': The requested URL returned error: 403
cheers.

**Comment by clebsonf** [comment]
@bruceyboy86 you can fork it here:

https://github.com/OctobearHub/octobear.org/fork

Apparently everything is ok, other users managed to fork, if the error persists, call me again

**Comment by TheInspiredConjurer** [comment]
I want to contribute to this as part of Hacktoberfest 2022, Please assign me this, Thanks

**Comment by Gw3i** [comment]
Hey :) Really nice project! 👍 I would like to contribute some resources 🚀 as a part of #hacktoberfest 🥳

**Comment by Znoy108x** [comment]
Can I contribute?

**Comment by tobySolutions** [comment]
Hey!! can this issue be assigned to me?

**Comment by haidarrifki** [comment]
hi @clebsonf i just made a PR here #19 please check it out, thanks!

**Comment by samanthatarrice** [comment]
Hi! I'd like to contribute. The resource I was thinking of adding is this one. Let me know if you think it would be a good one to add!

https://javascript30.com/

**Comment by jrafaaael** [comment]
Can I contribute?

**Comment by MonicaFidalgo** [comment]
Hi @clebsonf this a really good idea! Can I contribute? If so, can you please assign me to this? thank you :)

**Comment by PaolaDaft** [comment]
Hi✨ I'd like to contribute, can you assign it to me?
