### ISSUE TITLE
Update package.json version automatically

### ISSUE THREAD

**Issue by whoisclebs** [OctobearHub/octobear.org#53]
# -- Feature --

## Description
A viable solution would be to have an action that changes the version for each tag.

## Motivation
Updating the package version can be a boring and forgettable task. We need to automate this task.

**Comment by im-habib** [comment]
You can change this version while you are running GitHub Actions.
I hope you understood what I mean.
But unfortunately, if you aren't clear about what I mean then let's discuss about it. I hope, I can handle this issue.
