### ISSUE TITLE
add new events for community.

### ISSUE THREAD

**Issue by whoisclebs** [OctobearHub/octobear.org#8]
We need to add more events for the community. Each one can contribute with some link of an event for development or for another context.

The data file can be found [here](https://github.com/OctobearHub/octobear.org/blob/main/src/assets/data/programs.json). Add more links in it in the following template:

**Comment by zialink** [comment]
I'll like to be assigned this issue, I also want to be clear about the task, should I just get a link to an event for development and add it to the project or is there more to it?

**Comment by clebsonf** [comment]
Just a link with title, description, if possible image and deadline for registration. 

Example: 

```json
{
        "title": "Hacktoberfest 2022",
        "image": "https://user-images.githubusercontent.com/43012757/193366195-c23979e1-60fd-4195-95e3-b0372f8a3c75.png",
        "description": "Hacktoberfest is a month-long celebration of open source software run by DigitalOcean in partnership with GitHub and Twilio. Hacktoberfest is open to everyone in our global community!",
        "url": "https://hacktoberfest.digitalocean.com/",
        "end_date": "2022-10-31"
}
```

This issue can be assigned by multiple people

**Comment by zialink** [comment]
Ok

**Comment by clebsonf** [comment]
@KartikChinda Sure! We are accepting contributions to this issue. Good hacktoberfest!

**Comment by aparna03dubey** [comment]
@clebsonf I would like to contribute. Please assign it to me.

**Comment by Gw3i** [comment]
I would like to assign some events 👀

**Comment by MarcosLudgerio** [comment]
Hello! Can I help with this issue?

**Comment by aparna03dubey** [comment]
Please check if I've completed the task as you expected.

**Comment by Maaz-Code** [comment]
@clebsonf hey there, I also want to add some OSS programs and summits in the programs section. Kindly assign this issue to me too. I would then be making a corresponding PR. Thank you!
